esphome:
  name: dorfstatus-panel
  friendly_name: Dorfstatus-Panel

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret dorfstatus_panel_api_encryption_key

ota:
  - platform: esphome
    password: !secret dorfstatus_panel_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .chaosdorf.space

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dorfstatus-Panel Rescue"
    password: "0oHAjt4nzqxt"

captive_portal:

